---
# Create LXC containers on Proxmox VE (all entries in roles/proxmox_create_lxc/defaults/main.yml → proxmox_containers).
# Run from a host that can reach the Proxmox API.
#
# Required: Proxmox API token + root password for new containers (see vars/README.md).
# With vars file: make create-lxc  (or -e "@vars/proxmox_create_vars.yml")
#
- name: Create LXC containers on Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    proxmox_validate_certs: false
  roles:
    - proxmox_create_lxc
  tags:
    - lxc
