{
 "title": "Proxmox Homelab",
 "description": "Proxmox Virtual Environment Dashboard (Homelab)",
 "tags": [
  "Proxmox",
  "Prometheus",
  "Homelab"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(pve_node_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{instance=\"$instance\",template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit{instance=\"$instance\"} and on (id, instance) pve_guest_info)"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\", id=~\"node/.+\"}/pve_cpu_usage_limit{instance=\"$instance\", id=~\"node/.+\"}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\", id=~\"node/.+\"}/pve_memory_size_bytes{instance=\"$instance\", id=~\"node/.+\"}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\", id=~\"storage/.+\"}/pve_disk_size_bytes{instance=\"$instance\", id=~\"storage/.+\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 4, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(pve_disk_size_bytes{instance=\"$instance\", id=~\"storage/.+\"}, \"legend\", \"$2\", \"id\", \"^([^\\\\/]+\\\\/)*([^\\\\/]+)$\")",
     "legendFormat": "{{legend}}"
    }
   ]
  },
  {
   "title": "Guests Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes{instance=\"$instance\"}) * on(id, instance) group_left(name) pve_guest_info{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit{instance=\"$instance\"}) * on(id, instance) group_left(name) pve_guest_info{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes{instance=\"$instance\"}) * on(id, instance) group_left(name) pve_guest_info{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name) pve_guest_info{instance=\"$instance\"}",
     "legendFormat": "{{name}} recv"
    },
    {
     "expr": "rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name) pve_guest_info{instance=\"$instance\"}",
     "legendFormat": "{{name}} send"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "(rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_read_bytes{instance=\"$instance\"}[5m])) * on(id, instance) group_left(name) pve_guest_info{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}